### ISSUE TITLE
Light grey is not readable on light background

### ISSUE THREAD

**Issue by elboulangero** [ebassi/mutest#10]
Mutest displays timings using `LIGHT_GREY`color, and it doesn't really work for terminals with light background.

Here's a screenshot of mutest output on gnome-terminal, using the color theme "Solarized light".

![Screenshot from 2019-07-05 10-44-38](https://user-images.githubusercontent.com/1942580/60697133-08a90380-9f13-11e9-9e48-a1c45dd9ef42.png)

**Comment by ebassi** [comment]
Thanks for the report. I moved those sections to a dark grey instead.

**Comment by elboulangero** [comment]
Works for me, thanks!

![Screenshot from 2019-07-06 10-27-41](https://user-images.githubusercontent.com/1942580/60751069-79ffb980-9fda-11e9-9531-23268f280801.png)
